#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Ready to push changes!'

echo 'Running unit tests...'
dotnet husky run --name dotnet-test

echo 'Generate unit tests report...'
dotnet husky run --name reportgenerator-create

echo 'Completed pre-push changes'