#github action to build and test SFC.GeneralTemplate application

name: Build and Test SFC.GeneralTemplate Application

on:
  workflow_dispatch:  
  pull_request:
    branches: [ "master" ]

env:
  DOTNET_VERSION: 8.0.x 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install Redis
        run: sudo apt-get install -y redis-tools redis-server

      - name: Verify Redis
        run: redis-cli ping

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-restore --no-build --configuration Release --verbosity normal /p:CollectCoverage=true /p:Threshold=0 /p:ThresholdStat=total